filter:
    excluded_paths: [tests/*]

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

build:
    environment:
        php:
            version: 7.2
    dependencies:
        before:
            - composer require phpunit/phpunit:8 --dev
            - composer require seferov/typhp:^0.2.0 --dev
            - composer require phpstan/phpstan:^0.11.0 --dev
            - composer require squizlabs/php_codesniffer:3.* --dev
            - composer require nunomaduro/phpinsights:^1.11.1 --dev
            - composer require php-coveralls/php-coveralls:^2.0 --dev
            - composer require sempro/phpunit-pretty-print:^1.2.1 --dev
    tests:
        override:
            - php-scrutinizer-run
            - phpcs-run
            - vendor/bin/typhp
            - vendor/bin/phpinsights
            -   command: vendor/bin/phpunit --coverage-text --coverage-clover clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover
